import type { Metadata } from "next";
import { Cormorant_Garamond } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

// const cormorant = Cormorant_Garamond({
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700'], 
//   style: ['normal', 'italic'], 
//   variable: '--font-cormorant',
//   display: 'swap',
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
      <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
